---
title: "R Notebook"
output: html_notebook
---
```{r setup, include=FALSE}
	knitr::opts_chunk$set(echo = TRUE)
```
	
```{r}
	library(readr); library(dplyr); library(stringr); library(lubridate)
```

```{r}
plasticContainer <- list(
  greenBox=c("paper","scissor"),     # location 1
  redBox=c(1L,3L,2.5),               # location 2
  blueBox=c(TRUE,FALSE,TRUE,TRUE)    # location 3
)
```

```{r}
plasticContainer[c("greenBox")] # or plasticContainer[c(1,2)]
```

```{r}
plasticContainer[["greenBox"]] # or plasticContainer[[1]]
```

```{r}
plasticContainer$greenBox
```

```{r}
#如果上面要取出paper，請問要怎麼延伸拿取？ans1
plasticContainer[["greenBox"]][1]
```

```{r}
#如果上面要取出paper，請問要怎麼延伸拿取？ans2
plasticContainer$greenBox[1]
```
```{r}
#如果上面要取出paper，請問要怎麼延伸拿取？wrong version
plasticContainer["greenBox"][1] #1是指greenbox
```

```{r}
#如果上面要取出paper，請問要怎麼延伸拿取？ans3
plasticContainer["greenBox"]$greenBox[1]
```

```{r}
#如果上面要取出paper，請問要怎麼延伸拿取？ans4
plasticContainer["greenBox"][["greenBox"]][1]
```
#我是分隔線
```{r}
	install.packages("plotly")
```

```{r}
download.file("https://github.com/tpemartin/github-data/blob/master/plotly_4070_neda.Rda?raw=true",destfile = "plotly_4070_neda.Rda")
load("plotly_4070_neda.Rda")
library(plotly)
plotly_4070_neda
```

```{r}
plotly_4070_neda$x$layout$shapes[[1]]$opacity
```

```{r}
plotly_4070_neda$x$layout$shapes[[1]]$opacity <- 0.8
plotly_4070_neda
```

#我是分隔線
```{r}
library(readr); library(dplyr); library(stringr); library(lubridate)
```

```{r}
library(readr)
transcriptData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcript100_102.csv",
                  col_types = cols(
                    學期成績="n"
                  ))

totalCredits<-function(x){
  transcriptData[transcriptData$學號==x,]->subsample 
  subsample %>%
    mutate(
      及格=(學期成績>=60)
    ) %>%
    summarise(
      學號=學號[1],
      總修習學分數=sum(學分數),
      總實得學分數=sum(學分數[及格])
    )  
}
```

```{r}
transcriptData %>%
  filter(學屆==100,str_sub(學號,5,6)=="P1") -> subsample
subsample$學號 %>% unique -> 符合條件學號
```

```{r}
creditResults<-vector("list",length(符合條件學號))

for(i in seq_along(符合條件學號)){
  creditResults[[i]] <- totalCredits(符合條件學號[i])
}
```

#分隔

```{r}
library(readr)
library(tidyr)
libraryData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/libraryData2.csv")
libraryData %>%
  group_by(學院) %>%
  nest(.key="各院借閱資料") ->
  libraryDataNested
```

```{r}
library(dplyr)
libraryData %>%
  filter(學院=="人文學院")
```

```{r}
df <- data.frame(
  x = 1:3,
  y = c("a", "d,e,f", "g,h"),
  z = c("A","A","B"),
  stringsAsFactors = F
)
df %>% 
  group_by(z) %>%
  nest -> dfNested
```


