---
title: "R Notebook"
output: html_notebook
---

```{r}
library(readr); library(dplyr); library(stringr); library(lubridate)
libraryData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/library100_102.csv")
```

```{r}
mutate(libraryData, 
學院=as.factor(學院),
書籍館藏地=as.factor(書籍館藏地),
書籍類別=as.factor(書籍類別),
借閱時間=ymd_hms(借閱時間,tz="Asia/Taipei")
  ) -> libraryData
```

```{r}
minMax <- function(x){
max(libraryData$讀者借閱冊數) -> maxNumber
min(libraryData$讀者借閱冊數) -> minNumber
paste0("最大值： ",maxNumber, " 最小值： ",minNumber)}

minMax(libraryData$書籍出版日期)
```

```{r}
minMax2 <- function(x){
max(libraryData$讀者借閱冊數) -> maxNumber
min(libraryData$讀者借閱冊數) -> minNumber
paste0("最大值： ",maxNumber, " 最小值： ",minNumber) -> result
return(result)}
```

```{r}
libraryData$學院 == "人文學院" -> logIndex
libraryData[logIndex, ] -> subsample

libraryData$學院 == "社會科學院" -> logIndex
libraryData[logIndex, ] -> subsample2
```

```{r}
findMyCollege <- function(x){
  (libraryData$學院==x) -> logIndex
  libraryData[logIndex, ] -> subsample
  return(subsample)
}

findMyCollege("社會科學院") ->s
nrow(s)
```

```{r}

```







