---
title: "R Notebook"
output: html_notebook
---

```{r}
library(readr)
libraryData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/library100_102.csv")
```

```{r}
#資料中的書籍館藏地有那幾類？請將類別存在storageLocations物件中。[hint:使用levels()]
libraryData$書籍館藏地 %>% as.factor %>%
levels -> storageLocations
storageLocations
#同上
libraryData$書籍館藏地 <- as.factor(libraryData$書籍館藏地)
levels(libraryData$書籍館藏地) -> storageLocations
```

```{r}
# 0
allBorrowCount <- vector("numeric",18)
```

```{r}
i<-1
  # 1
  storageLocation_i <- storageLocations[i] 
  # 2
  numericalIndexForSubsample<-which(libraryData$書籍館藏地==storageLocation_i)
  subsample_i <- libraryData[numericalIndexForSubsample,]
  # 3
  borrowCount_i <- nrow(subsample_i)
  # 4
  allBorrowCount[[i]]<-borrowCount_i
```

```{r}
# 0
allBorrowCount <- vector("numeric",18)
for(i in c(1:18)){
  # 1
  storageLocation_i <- storageLocations[i] 
  # 2
  numericalIndexForSubsample<-which(libraryData$書籍館藏地==storageLocation_i)
  subsample_i <- libraryData[numericalIndexForSubsample,]
  # 3
  borrowCount_i <- nrow(subsample_i)
  # 4
  allBorrowCount[[i]]<-borrowCount_i  
}
```



```{r}
#請使用for loop算出每個學院的借書量。



```



