---
title: "R Notebook"
output: html_notebook
---

```{r}
StuDF <- data.frame(
  StuID=c(1,2,3,4,5),
  name=c("小明","大雄","胖虎","小新","大白"),
  score=c(80,60,90,70,50)
  )
StuDF[1,2 ]
StuDF[1,]
StuDF[c(1,4),]
StuDF[c(1,4),c(2,3)]
(StuDF$score >= 80)
(StuDF$name == "小新")
```

```{r}
StuDF[c(1, 2, 3),]
StuDF[c(1:3,5),]
c(1:3) # same as c(1,2,3)
c(5:7) # same as c(5,6,7)
c(1,5:7,10) #same as c(1,5,6,7,10)
```

```{r}
StuDF[c(T,F,F,F,F),c(F,T,F)]
StuDF[c(T,F,F,T,F),]
```

```{r}
as.character(StuDF$name) -> StuDF$name
```

```{r}
StuDF[c(1,4),]
StuDF[-c(1,4),]
```


```{r}
library(googlesheets)
gsSurvey<-gs_key("1mC9bnxj11NCNoOCw0Vmn4nxERbHtLjeGo9v9C9b2GDE")
classSurvey<-gs_read(gsSurvey,ws=1)
(classSurvey$性別 == "男")

(classSurvey$本學期學分數 > 20)

(classSurvey$性別 == "男" & 
    classSurvey$本學期學分數 > 20)
```
```{r}
(classSurvey$性別 == "男" |
classSurvey$本學期學分數 > 26)

classSurvey[(classSurvey$性別 == "男" &
classSurvey$本學期學分數 > 26),3]

```

```{r}
aaa<-c(3, 7, 9, 10)
aaa[3]
aaa[1:3]
```
```{r}
StuDF[c(1, 4), c(2)]
StuDF[, c(2)][c(1, 4)]

StuDF[, c(2)]->aa
aa[c(1, 4)]
```
```{r}
StuDF$name[c(2)]
```
```{r}
StuDF[,c(1,3)][c(1,4), ]
```



